// python -m grpc_tools.protoc -I=. --python_out=. --grpc_python_out=. path/to/schema.proto

syntax = "proto3";

package grpc_service;

/* message modality */
enum Mode {
  TEXT = 0;
  IMAGE = 1;
  AUDIO = 2;
  VIDEO = 3;
  NONE = 4;
}

/* peer info */
message Peer {
  oneof info_type {
    AgentInfo agent_info = 1;
    ToolInfo tool_info = 2;
  }
}

/* 注册信息 */
message AgentInfo {  // Agent注册信息
  string agent_id = 1;
  string address = 2;
  string name = 3; //可定义角色
  string domain = 4;      //可对Agent分组
  Mode input_mode = 5;
  Mode output_mode = 6;
  string description = 7;
  message AgentSkill {
    string skill_id = 1;
    string capability = 2;
  }
  repeated AgentSkill skills= 8;
  string version = 9;
}

message RegisterAgentResponse { // Agent注册响应信息
  bool success = 1;
  repeated Peer peers = 2;
}

message ToolInfo {  // Tool注册信息
  string tool_id = 1;
  string address = 2;
  string name = 3;
  string domain = 4;  //可对Tool分组
  Mode input_mode = 5;
  Mode output_mode = 6;
  string description = 7;
  map<string, string> arguments = 8;
  string version = 9;
}

message RegisterToolResponse { // Tool注册响应信息
  bool success = 1;
}


/* 节点清单获取 */
message GetNodesRequest {
  string agent_id = 1;  // 请求Agent的ID
  string domain = 2;
}

message GetNodesResponse {
  repeated Peer peers = 1;
}

/* Agent交互 */
message TaskInfo { // 任务信息
  string task_id = 1;
  repeated string parent_task_ids = 2;
  enum MessageType {
    TASK_QUEST = 0;      
    TASK_RESPONSE = 1;   
  }
  MessageType message_type = 3;
  enum Status {
    EXECUTING = 0;
    WAITING = 1;
    BREAK = 2;
    FINISH = 3;
  }
  Status status = 4;
}

message AgentMessage { // Agent消息
  string sender_id = 1;
  string receiver_id = 2;
  string session_id = 3;
  enum SessionStatus {
    START_QUEST = 0; 
    START_RESPONSE = 1; // 普通消息
    STOP_QUEST = 2;  // 结束交互
    STOP_RESPONSE = 3; 
  }
  SessionStatus session_status = 4;
  TaskInfo task_info = 5;
  oneof content {
    string text = 6;
    bytes binary = 7;
  }
  Mode content_mode = 8;
  string message_id = 9;
  string reply_to_message_id = 10; // 回复哪条消息(可选)
}

/* Tool调用 */
message ToolRequest {
  string sender_id = 1;
  string receiver_id = 2;
  string session_id = 3;
  string tool_name = 4;
  map<string, string> arguments = 5;
}

message ToolResponse {
  string sender_id = 1;
  string receiver_id = 2;
  string session_id = 3;
  bool success = 4;
  oneof content {
    string text = 5;
    bytes image = 6;
    bytes audio = 7;
    bytes embedded = 8;
  }
  string error_message = 9;
}

/*  Agent服务定义 */
service AgentService {
  // Agent之间双向流式通信接口
  rpc CallAgent(stream AgentMessage) returns (stream AgentMessage) {};
}


/*  Tool服务定义 */
service ToolService {
  // Tool调用
  rpc CallTool(ToolRequest) returns (ToolResponse) {};
}


/*  网关服务定义 */
service GatewayService {
  // Agent消息路由（双向流）
  rpc RouteAgentCalling(stream AgentMessage) returns (stream AgentMessage) {};

  // Tool调用路由
  rpc RouteToolCalling(ToolRequest) returns (ToolResponse) {};
  
  // Agent注册,返回节点清单
  rpc RegisterAgent(AgentInfo) returns (RegisterAgentResponse) {};

  // Tool注册
  rpc RegisterTool(ToolInfo) returns (RegisterToolResponse) {};

  // Agent获取节点清单
  rpc GetNodes(GetNodesRequest) returns (GetNodesResponse) {};

}