# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from atlink_aip.grpc_service import schema_pb2 as atlink__aip_dot_grpc__service_dot_schema__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in atlink_aip/grpc_service/schema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Agent服务定义 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallAgent = channel.stream_stream(
                '/grpc_service.AgentService/CallAgent',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Agent服务定义 
    """

    def CallAgent(self, request_iterator, context):
        """Agent之间双向流式通信接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallAgent': grpc.stream_stream_rpc_method_handler(
                    servicer.CallAgent,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_service.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_service.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Agent服务定义 
    """

    @staticmethod
    def CallAgent(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpc_service.AgentService/CallAgent',
            atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ToolServiceStub(object):
    """Tool服务定义 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallTool = channel.unary_unary(
                '/grpc_service.ToolService/CallTool',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolRequest.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolResponse.FromString,
                _registered_method=True)


class ToolServiceServicer(object):
    """Tool服务定义 
    """

    def CallTool(self, request, context):
        """Tool调用
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolRequest.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_service.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_service.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """Tool服务定义 
    """

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.ToolService/CallTool',
            atlink__aip_dot_grpc__service_dot_schema__pb2.ToolRequest.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GatewayServiceStub(object):
    """网关服务定义 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteAgentCalling = channel.stream_stream(
                '/grpc_service.GatewayService/RouteAgentCalling',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.FromString,
                _registered_method=True)
        self.RouteToolCalling = channel.unary_unary(
                '/grpc_service.GatewayService/RouteToolCalling',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolRequest.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolResponse.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/grpc_service.GatewayService/RegisterAgent',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentInfo.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.RegisterTool = channel.unary_unary(
                '/grpc_service.GatewayService/RegisterTool',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolBoxInfo.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.RegisterToolResponse.FromString,
                _registered_method=True)
        self.DeregisterNode = channel.unary_unary(
                '/grpc_service.GatewayService/DeregisterNode',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.DeregisterNodeRequest.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.DeregisterNodeResponse.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/grpc_service.GatewayService/GetNodes',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.GetNodesResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/grpc_service.GatewayService/Heartbeat',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.UpdateNodeInfo = channel.unary_unary(
                '/grpc_service.GatewayService/UpdateNodeInfo',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateNodeInfoRequest.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateNodeInfoResponse.FromString,
                _registered_method=True)
        self.SubscribeToUpdates = channel.unary_stream(
                '/grpc_service.GatewayService/SubscribeToUpdates',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateSubscriptionRequest.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.NodeUpdate.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/grpc_service.GatewayService/Unsubscribe',
                request_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UnsubscribeResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """网关服务定义 
    """

    def RouteAgentCalling(self, request_iterator, context):
        """Agent消息路由（双向流）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteToolCalling(self, request, context):
        """Tool调用路由
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Agent注册,返回节点清单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTool(self, request, context):
        """Tool注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterNode(self, request, context):
        """Node取消注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Agent获取节点清单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Agent和Tool心跳监测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNodeInfo(self, request, context):
        """节点信息更新
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToUpdates(self, request, context):
        """节点订阅更新
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """节点取消订阅
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteAgentCalling': grpc.stream_stream_rpc_method_handler(
                    servicer.RouteAgentCalling,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.SerializeToString,
            ),
            'RouteToolCalling': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteToolCalling,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolRequest.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.AgentInfo.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'RegisterTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTool,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.ToolBoxInfo.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.RegisterToolResponse.SerializeToString,
            ),
            'DeregisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterNode,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.DeregisterNodeRequest.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.DeregisterNodeResponse.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.GetNodesRequest.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.GetNodesResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.HeartbeatRequest.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.HeartbeatResponse.SerializeToString,
            ),
            'UpdateNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNodeInfo,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateNodeInfoRequest.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateNodeInfoResponse.SerializeToString,
            ),
            'SubscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUpdates,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateSubscriptionRequest.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.NodeUpdate.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UnsubscribeRequest.FromString,
                    response_serializer=atlink__aip_dot_grpc__service_dot_schema__pb2.UnsubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_service.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_service.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """网关服务定义 
    """

    @staticmethod
    def RouteAgentCalling(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpc_service.GatewayService/RouteAgentCalling',
            atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.AgentMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouteToolCalling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GatewayService/RouteToolCalling',
            atlink__aip_dot_grpc__service_dot_schema__pb2.ToolRequest.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GatewayService/RegisterAgent',
            atlink__aip_dot_grpc__service_dot_schema__pb2.AgentInfo.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GatewayService/RegisterTool',
            atlink__aip_dot_grpc__service_dot_schema__pb2.ToolBoxInfo.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.RegisterToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GatewayService/DeregisterNode',
            atlink__aip_dot_grpc__service_dot_schema__pb2.DeregisterNodeRequest.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.DeregisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GatewayService/GetNodes',
            atlink__aip_dot_grpc__service_dot_schema__pb2.GetNodesRequest.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.GetNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GatewayService/Heartbeat',
            atlink__aip_dot_grpc__service_dot_schema__pb2.HeartbeatRequest.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GatewayService/UpdateNodeInfo',
            atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateNodeInfoRequest.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateNodeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_service.GatewayService/SubscribeToUpdates',
            atlink__aip_dot_grpc__service_dot_schema__pb2.UpdateSubscriptionRequest.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.NodeUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GatewayService/Unsubscribe',
            atlink__aip_dot_grpc__service_dot_schema__pb2.UnsubscribeRequest.SerializeToString,
            atlink__aip_dot_grpc__service_dot_schema__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
